# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

variables:
  DOCKER_DRIVER: overlayfs
services:
  - docker:dind
before_script:
  - docker login --username gitlab-ci-token --password $CI_BUILD_TOKEN registry.gitlab.com
after_script:
  - docker logout registry.gitlab.com

build-master:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

deploy_to_swarm:
  stage: deploy
  script:
    - echo "$NETLIMY_TLSCACERT" > ~/.docker/ca.pem
    - echo "$NETLIMY_TLSCERT" > ~/.docker/cert.pem
    - echo "$NETLIMY_TLSKEY" > ~/.docker/key.pem
    - docker --tlsverify -H tcp://$NETLIMY_SERVER_IP:2376 stack deploy --with-registry-auth --compose-file=./production.yml netlimy
