version: "3.3"

services:
  netlimy:
    image: registry.gitlab.com/nukapi/netlimy:latest
    build:
      context: .
    volumes:
      - website:/website
      - updater_state:/updater_state
      - deployment:/deployment
    environment:
      - WEBSITE_GIT_REPO=https://github.com/siavash9000/netlimy.com.git

  nginx:
    image: nginx:1.13-alpine
    ports:
      - 80:80
    depends_on:
      - netlimy
    volumes:
      - deployment:/deployment
      - ./conf/nginx:/conf
    command: "nginx -c /conf/nginx_nossl.conf -g 'daemon off;'"

volumes:
  website:
  updater_state:
  deployment:
