version: "3.3"

services:
  serve:
    image: jekyll/jekyll:latest
    command: jekyll serve --config _config.yml --watch --verbose
    volumes:
      - ./website:/srv/jekyll
      - ./website/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
