version: "3.3"

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - 443:443
    deploy:
      replicas: 2
    depends_on:
      - nginx_letsencrypt
    volumes:
      - dehydrated:/etc/dehydrated/
      - well_known:/var/www/dehydrated
      - deployment:/deployment
    environment:
      - MAIN_DOMAIN=test.netlimy.com
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf.template
    command: envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && cat /etc/nginx/nginx.conf
  netlimy:
    image: registry.gitlab.com/nukapi/netlimy:latest
    ports:
      - 80:80
    volumes:
      - dehydrated:/etc/dehydrated/
      - well_known:/var/www/dehydrated
      - website:/website
      - updater_state:/updater_state
      - deployment:/deployment
    environment:
      - WEBSITE_GIT_REPO=https://github.com/siavash9000/netlimy.com.git
      - PRODUCTION=true
      - DOMAINS=test.netlimy.com
    command: /run.sh

volumes:
  dehydrated:
  well_known:
  website:
  updater_state:
  deployment:

configs:
  nginx:
    file: conf/nginx/nginx_production.conf