version: "3.3"

services:
  nginx:
    image: registry.gitlab.com/nukapi/netlimy:latest
    ports:
      - 443:443
    deploy:
      replicas: 2
    depends_on:
      - nginx_letsencrypt
    volumes:
      - dehydrated:/etc/dehydrated/
    command: "nginx -c /etc/nginx/nginx_ssl.conf -g 'daemon off;'"

  nginx_letsencrypt:
    image: registry.gitlab.com/nukapi/netlimy:latest
    ports:
      - 80:80
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    volumes:
      - dehydrated:/etc/dehydrated/
    command: /start_cert_cron.sh

volumes:
  dehydrated: