version: "3.3"

services:
  websitedeployer:
    image: registry.gitlab.com/nukapi/netlimy:latest
    volumes:
      - nginx:/website
      - nginx_cache:/var/cache/nginx
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
    volumes:
      - nginx:/website
      - nginx_cache:/var/cache/nginx
    deploy:
      replicas: 2

configs:
  nginx:
    file: ./conf/nginx/nginx.conf
volumes:
  nginx:
  nginx_cache: