version: "3.3"

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - 443:443
    deploy:
      replicas: 2
    depends_on:
      - nginx_letsencrypt
    volumes:
      - dehydrated:/etc/dehydrated/
      - well_known:/var/www/dehydrated
      - deployment:/deployment
    configs:
      - source: nginx
        target: /nginx_production.conf
    command: sh -c "sed -e 's/MAIN_DOMAIN/netlimy.com/' /nginx_production.conf > /etc/nginx/nginx_production.conf && nginx -c /etc/nginx/nginx_production.conf -g 'daemon off;'"

  netlimy:
    image: nukapi/netlimy:latest
    ports:
      - 80:80
    volumes:
      - dehydrated:/etc/dehydrated/
      - well_known:/var/www/dehydrated
      - website:/website
      - updater_state:/updater_state
      - deployment:/deployment
    environment:
      - WEBSITE_GIT_REPO=https://github.com/siavash9000/netlimy.com.git
      - PRODUCTION=true
      - DOMAINS=netlimy.com www.netlimy.com
    command: /run.sh

volumes:
  dehydrated:
  well_known:
  website:
  updater_state:
  deployment:

configs:
  nginx:
    file: conf/nginx/nginx_production.conf
