version: "3.3"

services:
  nginx:
    image: registry.gitlab.com/nukapi/netlimy:latest
    ports:
      - 80:80
    deploy:
      replicas: 2
    depends_on:
      - nginx_letsencrypt
    volumes:
      - ssl_certs: /etc/dehydrated/certs
    command: "nginx -c /etc/nginx/nginx_ssl.conf -g 'daemon off;'"

  nginx_letsencrypt:
    image: registry.gitlab.com/nukapi/netlimy:latest
    ports:
      - 80:80
    deploy:
      replicas: 2
    volumes:
      - ssl_certs: /etc/dehydrated/certs
    healthcheck:
      test:  test '$(ls -A "/etc/dehydrated/certs")'
    command: "nginx -c /etc/nginx/nginx_dehydrated.conf && CMD /dehydrated/dehydrated --cron --accept-terms --config /etc/dehydrated/config/conf"

volumes:
  ssl_certs: