version: "3.3"

services:
  nginx:
    image: registry.gitlab.com/nukapi/netlimy:latest
    ports:
      - 80:80
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
    deploy:
      replicas: 2

configs:
  nginx:
    file: ./conf/nginx/nginx.conf
