version: "3.3"

services:
  nginx:
    image: registry.gitlab.com/nukapi/netlimy:latest
    ports:
      - 443:443
    deploy:
      replicas: 2
    depends_on:
      - nginx_letsencrypt
    volumes:
      - dehydrated:/etc/dehydrated/
      - well_known:/var/www/dehydrated
    command: "nginx -c /etc/nginx/nginx_ssl.conf -g 'daemon off;'"

  dehydrated:
    image: registry.gitlab.com/nukapi/netlimy:latest
    ports:
      - 80:80
    deploy:
      replicas: 1
      restart_policy:
        delay: 48h
    volumes:
      - dehydrated:/etc/dehydrated/
      - well_known:/var/www/dehydrated
    command: /create_update_cert.sh

volumes:
  dehydrated:
  well_known: